### ISSUE TITLE
Milestone 3 Feeback

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/nameforme#92]
Congratulations on finishing milestone 3 group 3!  Nice work uploading your package to PYPI! Nice work on the Tests on R and setting up your R repo!  Below we list some specific feedback you can use to improve your project. We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project. If anything is unclear, please feel free to ask questions in this issue thread.

R package

- [x] At least 1 test fails ( - -20 accuracy)

<img width="400" alt="Screenshot 2023-01-30 at 3 10 26 PM" src="https://user-images.githubusercontent.com/45893111/215618409-a6fcfb1e-26ad-40cc-88c4-546b6c619a2e.png">

Python package

Greatjob! CICD is good, and Uploaded to PYPI

Great job, you’re at the final stretch. One milestone left :)

**Comment by eyrexh** [comment]
Hi Andy @andytai7,

I tested our group R package last week with zero errors and warnings. Also, I tried to test it again this night after seeing your feedback and got no error at all. Can you please show me the detailed error message? Thank you.


<img width="1279" alt="Screenshot 2023-01-30 at 22 21 28" src="https://user-images.githubusercontent.com/35082486/215682463-e02d2cd3-09a7-4652-b611-ada448828033.png">
<img width="1280" alt="Screenshot 2023-01-30 at 22 21 40" src="https://user-images.githubusercontent.com/35082486/215682472-4f68dc14-01f1-4276-9a7d-b47dc49c947e.png">
<img width="742" alt="Screenshot 2023-01-30 at 22 00 01" src="https://user-images.githubusercontent.com/35082486/215678569-5bdd3ee7-6ec2-4cb9-9e7e-fab0504d5f80.png">

**Comment by andytai7** [comment]
It looks like i pulled the Rstudio package yesterday when maybe some of the team members were playing around with the tests causing them to fail? That's my only reasonable explanation. 

As you can see below, all the tests pass, when i pull from the milestone repo. This was my mistake, therefore all the grades will be rewarded back. Good luck in milestone 4! 

![Uploading Screenshot 2023-01-31 at 2.30.13 PM.png…]()

**Comment by eyrexh** [comment]
No worries. Thank you for the explanation!
