### ISSUE TITLE
Milestone 4 Feedback

### ISSUE THREAD

**Issue by negsadr** [UBC-MDS/nameforme#94]
> **Congratulations on finishing milestone 4!** We can see you put a lot of work into this project, nice work!
Below we list some specific feedback you can use to improve your project.  
> We provide tick boxes for you to use in the future as you address these concerns to improve the final grade of your project.
> If anything is unclear, please feel free to ask questions in this issue thread.

---

## 1. GitHub actions workflow for continuous integration
rubric={mechanics:35}

Well done!

## 2. Documentation
rubric={reasoning:25}

Well done!

## 3. License checklist
rubric={reasoning:10}

Well done!

## 4. Initiate a package review request
rubric={mechanics:10}

- [x] The Python package review has not been opened and/or it is not using the template - **-5 mechanics**
- [x] The R package review has not been opened and/or it is not using the template - **-5 mechanics**

## 5. Specific expectations for this milestone
rubric={mechanics:10}

Well done!

## 6. Submission instructions
rubric={mechanics:10}

Well done!

**Comment by eyrexh** [comment]
Hi Negar @negsadr ,


Thank you for the feedback.
I have opened the issues for peer reviewing in the repo and other classmates have even finished the reviewing last week. I do not get it why the marks have been deducted. Please check the below link.
Python: https://github.com/UBC-MDS/software-review-2023/issues/20
R: https://github.com/UBC-MDS/software-review-2023/issues/14

If you mean the links have not been provided in the Milestone 4 submission, I checked the submission requirements again and it does not mention the peer review issue links.

![8A09CB0B-098E-4488-9E10-31EA2618E363](https://user-images.githubusercontent.com/35082486/218273959-93c2a34b-6517-463f-81b2-7140b7c2ec0d.png)

Regards,
Eyre

**Comment by negsadr** [comment]
Hi @eyrexh
Thanks for noting that! I'm modifying your grade!
good luck!

**Comment by eyrexh** [comment]
Thank you!
